/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Charts;

import javafx.application.Application;

public class App {

    public static void main(String[] args) {
    	Application.launch(Launcher.class, args);
    }
}
