/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Charts;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

import model.Coin;
import model.QueryBuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        String query = new QueryBuilder().selectCoin(Coin.BITCOIN).build();
        try {
			URL url = new URL(query);
			HttpURLConnection connection = (HttpURLConnection) url.openConnection();
			connection.setRequestProperty("accept", "application/json");

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        

    }
}
