/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Charts;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

import model.Coin;
import model.QueryBuilder;
import model.Request;

public class App {

    public static void main(String[] args) {
    	Request.price(Coin.BITCOIN);
    	
    }
}
